### ISSUE TITLE
Base API 작성하고 AuthService::Authorizer를 서비스로부터 옮겨넣기

### ISSUE THREAD

**Issue by jungin-jin-choi** [taeheon-ki/ringle_music_assignment#12]
```
def call
      auth_result = AuthService::Authorizer.call(request: @request)
      return auth_result if auth_result.is_a?(Hash)
      @user_id = auth_result
```
이 부분이 대부분의 서비스에서 반복이 되고 있습니다.
일단 이 서비스들에서 모두 user authentication 기능까지 수행할 필요는 없을 것 같습니다. (서비스는 구체적이고 좁은 기능 하나를 수행하는 것이 좋습니다.)

Authentication을 수행하는 모듈을 하나 작성하고 > 이를 helper로 등록해놓은 최상위 API를 작성하고 > 다른 API들이 이 최상위 API를 상속하게끔 구현하면 좋을 것 같습니다.

참고
https://github.com/ruby-grape/grape#helpers -> Grape API의 `helpers` 에 대한 설명

저희 beta 레포에서 
```
module Beta
  module V4
    class Base < Grape::API
..
      helpers AuthHelpers
```
참고해보세요

**Comment by taeheon-ki** [comment]
related to : #9 #6
